### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by Curtaingit** [supsunc/swing-jcef-spring#1]
\swing-jcef-spring-master\src\main\lib\jcef\lib\win64\libcef.dll: %1 不是有效的 Win32 应用程序。

**Comment by supsunc** [comment]
window和文件之间兼容问题？参考 https://blog.csdn.net/u013642500/article/details/102655124 重新构建 jcef 吧

**Comment by Curtaingit** [comment]
重新构建     编译可以， 执行测试和打包有问题。  有遇到过吗
![1694487913224](https://github.com/supsunc/swing-jcef-spring/assets/31627168/9467d141-7bac-41be-8e88-8362a88c02f8)

**Comment by Curtaingit** [comment]
不知道是不是git的问题  下载的libcef.dll只有1KB   本地重新构建的188MB

**Comment by supsunc** [comment]
文件通过LFS存储的，你是不是没安装LFS

**Comment by Curtaingit** [comment]
git windows应该默认集成了。

**Comment by Curtaingit** [comment]
通过参考 https://blog.csdn.net/u013642500/article/details/102655124 重新构建 jcef   解决。
